name: Manual Docker test
on: workflow_dispatch
jobs:
  docker_helloworld:
    runs-on: centos764_4
    steps:
      - name : whoareu
        run : whoami
      - name: Docker
        run: docker version
      - name: run hello-world
        run : docker run hello-world
