name: Manual Docker test
on: workflow_dispatch
jobs:
  docker_helloworld:
    runs-on: docker-runner-05
    steps:
      - name : whoareu
        run : whoami
      - name: Docker
        run: docker version
