# This is a basic workflow that is manually triggered

name: Manual workflow
on: workflow_dispatch
jobs :
  job1:
    runs-on: ubuntu-latest
    steps:
      -name:  Python
      run: echo "Hello"
    
