name: Manual Workflow

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name : Hello
        run: echo "Hello World"
      - name : Listing
        run: ls -lart
      - name : python
        run: python3 --version
    
