name: Manual Workflow - greeting

on: [workflow_dispatch]
env:
  env_var : ${{ vars:APPLICATION_NAME }}
jobs:
  greeting:
    runs-on: [self-hosted]
    steps:
      - name : Hello
        run: uname ; echo "Hello World"
      - name : Listing
        run: ls -lart
      - name : python
        run: python3 --version
      - name : environment
        run:  set
      - name : showvariable
        run : echo $env_var
