name: Manual Ubuntu Workflow

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: self-hosted
    steps:
      - name : Hello
        run: uname ; echo "Hello World"
      - name : Listing
        run: ls -lart
      - name : python
        run: python3 --version
      - name : environment
        run:  set
    
