name: demo_of_variable_in_jobs
on: workflow_dispatch
env:
  mascot: Mona
  env_var: ${{ vars.APPLICATION_NAME }}
  password: ${{ secrets.PASSWORD }}
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: self-hosted
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Mona
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Octocat
        env:
          mascot: Octocat
  linux_job:
    runs-on: ubuntu-latest
    env:
      mascot: Tux
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Tux
      
  build:
    runs-on: self-hosted
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build_step
        run: |
          echo "--- Build ---"
          export BUILD_ID=$RANDOM
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo ./deploy --build ${{ needs.build.outputs.build_id }}
  debug:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v3
      - run: echo $BUILD_ID failed
